[[constraint]]
  name = "github.com/lusis/go-slackbot"


[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
